services:
  sikeu_core_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sikeu_core_app
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - sikeu_core_node_modules:/app/node_modules
      - ./logs:/app/logs
    restart: on-failure
    networks:
      - sikeu_core_network

volumes:
  sikeu_core_node_modules:
    name: sikeu_core_node_modules
    driver: local

networks:
  sikeu_core_network:
    name: sikeu_core_network
    driver: bridge
